# Generated by Django 6.0.6 on 2026-06-24 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencename', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencename',
            name='lateregistration_fee',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencename',
            name='lateregistration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencename',
            name='normalregistration_fee',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
