# Generated by Django 6.0.6 on 2026-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencename', '0002_conferencename_lateregistration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencename',
            name='conferencedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencename',
            name='venue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
