# Generated by Django 6.0.6 on 2026-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencename', '0003_conferencename_conferencedate_conferencename_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencename',
            old_name='closing_date',
            new_name='conferenceenddate',
        ),
        migrations.AddField(
            model_name='conferencename',
            name='conferencestartdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
