# Generated by Django 6.0.6 on 2026-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencename', '0004_rename_closing_date_conferencename_conferenceenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencename',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
