# Generated by Django 6.0.6 on 2026-06-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencename', '0005_alter_conferencename_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencename',
            name='conferencedate',
        ),
    ]
