# Generated by Django 6.0.6 on 2026-06-25 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferencename', '0002_conferencename_lateregistration_fee_and_more'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confregdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=200)),
                ('accompany', models.CharField(max_length=20)),
                ('wacsfellow', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('subspeecialty', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('conferencename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencename.conferencename')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
