# Generated by Django 6.0.6 on 2026-06-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confregdetails', '0002_alter_confregdetail_accompany_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confregdetail',
            old_name='subspeecialty',
            new_name='subspecialty',
        ),
    ]
