# Generated by Django 6.0.6 on 2026-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confregdetails', '0004_alter_confregdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confregdetail',
            name='accompany',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+'), ('10+', '10+')], max_length=5),
        ),
        migrations.AlterField(
            model_name='confregdetail',
            name='subspecialty',
            field=models.CharField(blank=True, choices=[('Conservative Dentistry', 'Conservative Dentistry'), ('Community Dentistry', 'Community Dentistry'), ('Oral and Maxillofacial Surgery', 'Oral and Maxillofacial Surgery'), ('Orthodontics', 'Orthodontics'), ('Oral Medicine', 'Oral Medicine'), ('Oral Pathology', 'Oral Pathology'), ('Oral and Maxillofacial Radiology', 'Oral and Maxillofacial Radiology'), ('Periodontology', 'Periodontology'), ('Prosthodontics', 'Prosthodontics'), ('Paediatric Dentistry', 'Paediatric Dentistry'), ('Anterior Segment/Cornea', 'Anterior Segment/Cornea'), ('Comprehensive', 'Comprehensive'), ('Glaucoma', 'Glaucoma'), ('Medical Retina', 'Medical Retina'), ('Neurophthalmology', 'Neurophthalmology'), ('Oculoplasty', 'Oculoplasty'), ('Paediatric Ophthalmology', 'Paediatric Ophthalmology'), ('Vitreo-Retina Surgery', 'Vitreo-Retina Surgery'), ('Public Health in Eye Care (PHEC)', 'Public Health in Eye Care (PHEC)'), ('Cardiothoracic', 'Cardiothoracic'), ('General', 'General'), ('Neuro', 'Neuro'), ('Paediatrics', 'Paediatrics'), ('Plastic & Reconstructive', 'Plastic & Reconstructive'), ('Urology', 'Urology')], max_length=200, null=True),
        ),
    ]
