# Generated by Django 6.0.6 on 2026-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confregdetails', '0005_alter_confregdetail_accompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confregdetail',
            name='registration_category',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Exibitors', 'Exibitors'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
