# Generated by Django 6.0.6 on 2026-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confregdetails', '0006_confregdetail_registration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confregdetail',
            name='registration_category',
            field=models.CharField(blank=True, choices=[('', 'Select Registration Category'), ('Trainee', 'Trainee'), ('Exhibitor', 'Exhibitor'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
