# Generated by Django 6.0.4 on 2026-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('reviewer', 'Reviewer'), ('admin', 'Admin'), ('staff', 'Staff')], default='candidate', max_length=20),
        ),
    ]
